### ISSUE TITLE
Strange Overflow Behavior

### ISSUE THREAD

**Issue by amadeus** [Shougo/pum.vim#10]
As you can see from this screenshot, I am getting some strange overflow behavior. Is there something with my configuration I should be aware of?

<img width="1233" alt="CleanShot 2021-10-19 at 13 53 25" src="https://user-images.githubusercontent.com/83376/137988985-d1533e2b-2658-42aa-95ec-696f501bd602.png">

**Comment by Shougo** [comment]
I have tested `wrap` behavior.  But I cannot reproduce it.
So I need the minimal config...
