### ISSUE TITLE
Popup closed when whole rewrites pre inserted word with feedkeys

### ISSUE THREAD

**Issue by kuuote** [Shougo/pum.vim#12]
# Problem

Popup closed when whole rewrites pre inserted word with `setline_insert` option is `v:false`

# To Reproduce

1. Prepare following vimrc

```vim
set runtimepath+=~/pum.vim
inoremap <C-n>   <Cmd>call pum#map#insert_relative(+1)<CR>
inoremap <C-p>   <Cmd>call pum#map#insert_relative(-1)<CR>
let words = map(['foo', 'foobar', 'foobarbaz'], '{"word": v:val, "equal": v:true, "icase": v:true}')
autocmd TextChangedI * eval col('.') == 2 && pum#open(1, words)
```

2. Run `vim -u vimrc -N`

3. Type any characters and insert candidate
   (Note: When `"fo", "foo", "foob"...`, it works fine.)

# Environment

Vim 8.2.3565
Neovim v0.6.0-dev+515-gd918759de
pum.vim https://github.com/Shougo/pum.vim/commit/b03c25686074575938563bf9daded069c93fb519

**Comment by matsui54** [comment]
This line seems to cause this problem.
https://github.com/Shougo/pum.vim/blob/b03c25686074575938563bf9daded069c93fb519/autoload/pum/map.vim#L191

**Comment by Shougo** [comment]
Fixed.
