### ISSUE TITLE
Auto Imports Seem Broken With ddc/pum

### ISSUE THREAD

**Issue by amadeus** [Shougo/pum.vim#13]
It appears that when selecting an autoimport item from pum selection menu, the appropriate imports are not added:

Using pum.vim:

https://user-images.githubusercontent.com/83376/143725022-deffa699-7860-4e71-a1a1-36861892fbcf.mp4

Using built in completion menu:

https://user-images.githubusercontent.com/83376/143725031-c5dc1925-28c6-4a41-b3d8-d64ee047f77f.mp4

Notice how in this second one, the import gets added up top automatically?

**Comment by Shougo** [comment]
What plugins do you use?
We have not ESP skills.

I think your auto import plugins does not support `pum.vim`.
`pum.vim` is not native menu.
I think the plugin depends on `CompleteDone`.
But `CompleteDone` cannot call it.
`CompleteDone` depends on `v:completed_items`, but plugins cannot set the variable.

**Comment by amadeus** [comment]
I use ALE for the LSP side of things, and most certainly it does not support that event, I'll take a look and see if there's any way to customize this. Cheers!

**Comment by amadeus** [comment]
For anyone who may find this later, simply using this autocmd should fix auto import issues with ale as a DDC source

```
augroup DDCCompletions
  autocmd!
  autocmd User PumCompleteDone call ale#completion#HandleUserData(g:pum#completed_item)
augroup END
```

**Comment by amadeus** [comment]
I actually ran into another issue with this, however I never got around to reporting it. Unfortunately my fix above ends up introducing another issue. In cases where autoimports are added, I get the following error in vim:

```
Error detected while processing InsertCharPre Autocommands for "*"..function <SNR>238_check_skip_count[13]..<lambda>244[1]..pum#close[1]..<SNR
>232_complete_done[12]..User Autocommands for "PumCompleteDone"..function ale#completion#HandleUserData[18]..ale#code_action#HandleCodeAction[
5]..ale#code_action#ApplyChanges[99]..ale#util#SetBufferContents:
line   17:
E578: Not allowed to change text here
Press ENTER or type command to continue
```

**Comment by Shougo** [comment]
Sorry.  I cannot fix the problem.
pum.vim uses `InsertCharPre` autocmd to detect user input, but it cannot change current text.
So the auto import feature does not work.

I don't know the solution.  No magic.

**Comment by Shougo** [comment]
I have added the error ignore.
I think you have selected the candidate and input after the text.
It does not work.
