### ISSUE TITLE
Feature Request: Option to not select first result

### ISSUE THREAD

**Issue by amadeus** [Shougo/pum.vim#14]
I have a strong muscle memory from the native completion system where no option from the completion is selected when the popout shows until I press like `<c-n>` or `<c-y>`, would it possible to add?

It creates a bit of a UX inconsistency in that on first showing we have an item selected, but the input is not updated, if I press `<c-n>`, I move to the next item, the input gets updated to the new string, now if I go back up once, the input is updated to the first string:

https://user-images.githubusercontent.com/83376/143837553-840b2c20-b54e-4fa9-b0c1-1c7ed1d43f2f.mp4

I understand some people may prefer this, but it would be nice to at least have an option to not have any option selected at first

**Comment by Shougo** [comment]
set completeopt-=noselect

I think you have changed completeopt.

**Comment by amadeus** [comment]
Ahh, I didn't know it inherited from `completeopt` settings. Was there a note about this in the docs somewhere that I missed?

**Comment by Shougo** [comment]
```
Q: I want to use the auto select feature.

A: You can use it by the 'completeopt' option. >

	set completeopt+=noinsert
```
