### ISSUE TITLE
Cannot auto expand snippet when use with ddc.vim.

### ISSUE THREAD

**Issue by PHSix** [Shougo/pum.vim#21]
I use `ddc.vim` and `pum.vim` to impove completion menu. But I found that if I use `pum.vim` to insead of then native completion menu, snippet always cannot auto expand after `pum#map#confirm` called.(I have test and get the same result between neovim native lsp and vsnip)
**without use `pum.vim`:**

https://user-images.githubusercontent.com/57695072/173222506-73f4237a-b9eb-4b0b-a54e-635a2e0bb2f9.mp4

**with use `pum.vim`:**

https://user-images.githubusercontent.com/57695072/173222533-bab9f909-714b-449a-b740-2b26503838bd.mp4

**Comment by Shougo** [comment]
pum.vim does not support `CompleteDone` autocmd.  You need to emulate the event like this.

Note: It is for ale plugin. 

	 autocmd User PumCompleteDone
	 \ call ale#completion#HandleUserData(g:pum#completed_item)

**Comment by Shougo** [comment]
For vsnip plugin, you need to install "vim-vsnip-integ" plugin and please read
the documentation.

	https://github.com/hrsh7th/vim-vsnip-integ

**Comment by PHSix** [comment]
> For vsnip plugin, you need to install "vim-vsnip-integ" plugin and please read the documentation.
> 
> https://github.com/hrsh7th/vim-vsnip-integ

I have found some solution to deal with this problem in [vim-vsnip-integ/doc](https://github.com/hrsh7th/vim-vsnip-integ/blob/master/doc/vsnip_integ.txt#L36).
Now it works fine, thanks for your reply.
