### ISSUE TITLE
Tab indentation not working when inoremap to `pum#map#insert_relative()`

### ISSUE THREAD

**Issue by yabeenico** [Shougo/pum.vim#24]
# Problem
If follow the steps of the README.md, and set the inoremap in ~/.vimrc like below, 

```
inoremap <Tab>   <Cmd>call pum#map#insert_relative(+1)<CR>
inoremap <S-Tab> <Cmd>call pum#map#insert_relative(-1)<CR>
```

increment/decrement function doesn't work when type \<Tab>/\<S-Tab> in insert mode.

Is it expected behavior?

# My Solution
I resolved the problem by defining `my_insert_relative()` and `inoremap <Tab> my_insert_relative()` like this:

```
function! s:my_insert_relative(number)
    if pum#visible()
        call pum#map#insert_relative(a:number)
    else
        if a:number > 0
            call feedkeys("\<Tab>", 'n')
            " `call feedkeys("\<C-o>>", 'n')` does't result expected behavior when cursor is not on a first character of a line
        else
            " call feedkeys("\<S-Tab>", 'n') unexpectedly feeds <Tab> key.
            " And I think there might be a more appropriate way than "\<C-o><<", but I don't know it.
            call feedkeys("\<C-o><<", 'n')
        endif
    endif
endfunction

inoremap <Tab>   <Cmd>call <SID>my_insert_relative(+1)<CR>
inoremap <S-Tab> <Cmd>call <SID>my_insert_relative(-1)<CR>
```

# Proposal
I propose change README.md or implementation of `pum#map#insert_relative()` like above.

Consideration: pass 'n' option to `feedkeys()` disables re-mapping fed keys, so changing the implementation of `pum#map#insert_relative()` might lost some flexibility.

# Other
The name of the argument  of `pum#map#insert_relative()`  is:
- `delta` in the code.
  - https://github.com/Shougo/pum.vim/blob/b12b805d06f5845cf96249319b21ad3fb5ab2103/autoload/pum/map.vim#L67
- `number` in the help.
  - https://github.com/Shougo/pum.vim/blob/b12b805d06f5845cf96249319b21ad3fb5ab2103/doc/pum.txt#L245

Would they be standarized?

**Comment by Shougo** [comment]
I use this solution.

```vim
  inoremap <silent><expr> <TAB>
        \ pum#visible() ? '<Cmd>call pum#map#insert_relative(+1)<CR>' :
        \ (col('.') <= 1 <Bar><Bar> getline('.')[col('.') - 2] =~# '\s') ?
        \ '<TAB>' : ddc#manual_complete()
```

> increment/decrement function doesn't work when type <Tab>/<S-Tab> in insert mode.

> Tab indentation not working when inoremap to pum#map#insert_relative()

I don't understand.  Because your title and description are inconsistent.

> Is it expected behavior?

It is expected behavior.  You have overwritten mappings.
You need to know what you are done.

> I propose change README.md or implementation of pum#map#insert_relative() like above.

I don't change the documentation.  It is *your* desired behavior.
Users need to consider what is the best mapping.  It is my plugins policy.

> Would they be standarized?

I have standardized.

**Comment by Shougo** [comment]
I have removed `<Tab>`/`<S-Tab>` mappings from example.
It is not for all users.
