### ISSUE TITLE
Max vertical items

### ISSUE THREAD

**Issue by Guergeiro** [Shougo/pum.vim#28]
Is there a way to limit the amount of items it shows but still allow them to be scrollable? Basically a `max_horizontal_items` but for vertical menu.

My use case is simple, I have multiple sources that populate `pum.vim`. Say I have 5 sources and each gives 5 candidates for completion. This will produce a total of 25 items, which means my completion window will get big. Would be nice to have it maxed, for example, 7 items and be scrollable.

**Comment by Shougo** [comment]
Oh, it is not implemented yet.
I will add it later.

**Comment by Shougo** [comment]
Fixed.

**Comment by Guergeiro** [comment]
Can confirm is working! Thanks!
