### ISSUE TITLE
Executing `pum#map#cancel` after `pum#map#insert_relative` breaks input text for some ddc sources  

### ISSUE THREAD

**Issue by azufr** [Shougo/pum.vim#31]
**Warning: I will close the issue without the minimal init.vim and the
reproduction instructions.**

# Problems summary

Thank you for creating many great plugins. 
When executing `pum#map#cancel` after `pum#map#insert_relative`, the inserted text does not revert to original input text.
This weird behaviour only happens for some `ddc` sources(nvim-lsp, and vsnip at the moment) and does not happen in around source.

## Expected

Executing `pum#map#cancel` should revert the inserted text to the original input text. 

## Environment Information (Required!)

- pum.vim version(SHA1): b927e1ab604d426581c0608fa17ecd7890aa8d8f

- OS: Arch Linux

- neovim/Vim `:version` output:

```
NVIM v0.8.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

## Provide a minimal init.vim/vimrc without plugin managers (Required!)

```lua
" Your minimal init.lua
vim.opt.runtimepath:append({ '~/.dein/repos/github.com/vim-denops/denops.vim' })
vim.opt.runtimepath:append({ '~/.dein/repos/github.com/Shougo/ddc.vim' })
vim.opt.runtimepath:append({ '~/.dein/repos/github.com/Shougo/ddc-around' })
vim.opt.runtimepath:append({ '~/.dein/repos/github.com/tani/ddc-fuzzy' })
vim.opt.runtimepath:append({ '~/.dein/repos/github.com/hrsh7th/vim-vsnip' })
vim.opt.runtimepath:append({ '~/.dein/repos/github.com/hrsh7th/vim-vsnip-integ' })
vim.opt.runtimepath:append({ '~/.dein/repos/github.com/rafamadriz/friendly-snippets' })
vim.opt.runtimepath:append({ '~/.dein/repos/github.com/Shougo/ddc-ui-pum' })
vim.opt.runtimepath:append({ '~/.dein/repos/github.com/Shougo/pum.vim' })

vim.opt.completeopt = { 'menu', 'menuone', 'noinsert' }
vim.fn['pum#set_option']('use_complete', false)
vim.fn['pum#set_option']('scrollbar_char', '')
local ddc_opts = {
    ui = 'pum',
    autoCompleteEvents = { 'InsertEnter', 'TextChangedI', 'TextChangedP', 'CmdlineChanged', 'CmdlineEnter' },
    sources = { 'around', 'vsnip' },
    sourceOptions = {
        _ = {
            matchers = { 'matcher_fuzzy' },
            sorters = { 'sorter_fuzzy' }
        },
        ['vsnip'] = {
            mark = "[vs]",
            dup = 'keep',
            ignoreCase = true,
        },
        ['around'] = {
            mark = '[A]'
        }
    }
}

vim.fn['ddc#custom#patch_global'](ddc_opts)
vim.fn['ddc#enable']()

vim.cmd([[autocmd User PumCompleteDone call vsnip_integ#on_complete_done(g:pum#completed_item)]])

vim.keymap.set('i', '<C-y>', '<cmd>call pum#map#confirm()<cr>')
vim.keymap.set('i', '<C-e>', '<cmd>call pum#map#cancel()<cr>')
vim.keymap.set('i', '<C-n>', '<cmd>call pum#map#insert_relative(+1)<cr>')
vim.keymap.set('i', '<C-p>', '<cmd>call pum#map#insert_relative(-1)<cr>')
```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. Save above settings to `min_init.lua`
2. Start neovim and edit python file (I think it should be reproduced with other filetypes too)
   ```
      nvim -Nu min_init.lua test.py
   ```
3. Please refer to screencast for detail

### Unexpected Behaviour (pum#cancel on vsnip source entry)

![unexpected_behaviour](https://user-images.githubusercontent.com/859197/202827833-5ea7c2bc-6b23-4ba6-965c-41dd2d47b054.gif)

### Expected Behaviour (pum#cancel on around source entry)

![expected_behaviour](https://user-images.githubusercontent.com/859197/202827851-9da37577-99a1-4eac-b452-224cd8cfb50a.gif)

## Upload the log messages by `:redir` and `:message` (if errored)

No error messages.

**Comment by Shougo** [comment]
Fixed.

**Comment by azufr** [comment]
Can confirm it is fixed. Thanks.
