### ISSUE TITLE
`CompleteDone` called two times at `use_complete` is enabled.

### ISSUE THREAD

**Issue by kuuote** [Shougo/pum.vim#32]
# Problems summary
`CompleteDone` called two times at `use_complete` is enabled.
For example, expand of vsnip source was duplicate.

## Expected
Want to call `CompleteDone` only once.

## Environment Information (Required!)

- pum.vim version(SHA1): 43f585f0eada1e3dfb100551fdb7771c9b14bfaa

- OS: Arch Linux

- neovim/Vim `:version` output:

```
NVIM v0.9.0-dev-368+g5eb5f4948-dirty
Build type: Debug
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions     -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security     -fstack-clash-protection -fcf-protection -Wp,-U_FORTIFY_SOURCE -Wp,-D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=1 -I/data/builder/src/neovim/src/neovim/build/cmake.config -I/data/builder/src/neovim/src/neovim/src -I/data/builder/src/neovim/src/neovim/.deps/usr/include -I/usr/include -I/data/builder/src/neovim/src/neovim/build/src/nvim/auto -I/data/builder/src/neovim/src/neovim/build/include
Compiled by root

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```

## Provide a minimal init.vim/vimrc without plugin managers (Required!)

```vim
function s:add(repo)
  let path = '/tmp/plug/' .. a:repo
  if !isdirectory(path)
    execute '!git clone --depth=1 https://github.com/' .. a:repo .. ' ' .. path
  endif
  execute 'set rtp^=' .. path
endfunction

call s:add('Shougo/ddc-ui-pum')
call s:add('Shougo/ddc.vim')
call s:add('Shougo/pum.vim')
call s:add('hrsh7th/completion-snippet')
call s:add('hrsh7th/vim-vsnip')
call s:add('hrsh7th/vim-vsnip-integ')
call s:add('vim-denops/denops.vim')

let g:vsnip_snippet_dir = '/tmp/plug/hrsh7th/completion-snippet/snippets'
call ddc#custom#patch_global('ui', 'pum')
call ddc#custom#patch_global('sources', ['vsnip'])
call ddc#enable()
inoremap <C-n>   <Cmd>call pum#map#insert_relative(+1)<CR>
inoremap <C-y>   <Cmd>call pum#map#confirm()<CR>
call pum#set_option('use_complete', v:true)
```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. execute `nvim -u init.vim`
2. set filetype to Vim script `:setf vim`
3. type `itry<C-n><C-y>` to expand snippet.
4. type any key(accidentally expand snippet at this time.)

## Screen shot (if possible)
![movie](https://user-images.githubusercontent.com/36663503/203311066-f0307254-dc64-4750-b8a6-8b28be6f2d95.gif)

**Comment by Shougo** [comment]
OK.  I have reproduced the problem and I get the reason.

But it does not mean I can fix the problem.

`CompleteDone` is called twice.

`type itry<C-n><C-y> to expand snippet.`

`CompleteDone` is called by `pum.vim`

`type any key(accidentally expand snippet at this time.)`

`CompleteDone` is called and break your buffer by Vim.

You have set `use_complete`.  It means if you input texts `CompleteDone` is fired.

Solution:  `vim-vsnip-integ` should support `PumCompleteDone` autocmd instead.

I cannot fix the problem in `pum.vim` side.
