### ISSUE TITLE
Unnecessary `...` are displayed with `padding: v:ture` in command line popup window.

### ISSUE THREAD

**Issue by ryota2357** [Shougo/pum.vim#37]
# Problems summary

When the `padding` option is set to `v:true`, the unnecessary `...` are displayed in the command line completion popup window.

This occurs with both neovim and vim.

## Expected

The `...` are not displayed, like the `padding` option is set to `v:false`.

## Environment Information (Required!)

- pum.vim version(SHA1): c981ac0d3de3ca645ee9538403c5ca68d93cb5a6

- OS: macOS

- neovim/Vim `:version` output:

```
NVIM v0.10.0-dev-1709+gef64e225f-Homebrew
Build type: Release
LuaJIT 2.1.0-beta3

      システム vimrc: "$VIM/sysinit.vim"
       省略時の $VIM: "/opt/homebrew/Cellar/neovim/HEAD-ef64e22/share/nvim"

Run :checkhealth for more info
```

## Provide a minimal init.vim/vimrc without plugin managers (Required!)

```vim
if !has("nvim")
  set nocompatible
  filetype plugin indent on
  syntax enable
endif

let s:plugins = [
      \ 'vim-denops/denops.vim',
      \ 'Shougo/ddc.vim',
      \ 'Shougo/pum.vim',
      \ 'Shougo/ddc-ui-pum',
      \ 'Shougo/ddc-source-cmdline',
      \ ]

for item in s:plugins
  execute 'set runtimepath+=~/.cache/dein/repos/github.com/' . item
endfor

call ddc#custom#patch_global(#{
 \   ui: 'pum',
 \   cmdlineSources: ['cmdline'],
 \   autoCompleteEvents: ['InsertEnter', 'TextChangedI', 'TextChangedP', 'CmdlineEnter', 'CmdlineChanged'],
 \ })

call pum#set_local_option('c', #{
  \   padding: v:true,
  \   min_width: 50,
  \ })

nnoremap : <Cmd>call ddc#enable_cmdline_completion()<CR>:

call ddc#enable()
```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. Start neovim.
2. Press `:` to enter the command line.
3. Input `ca` and then get completion.

## Screen shot (if possible)

<img width="506" alt="スクリーンショット 2023-05-18 21 15 15" src="https://github.com/Shougo/pum.vim/assets/61523777/a284bcaf-c49a-4050-a58a-ea36ae540ff8">

**Comment by Shougo** [comment]
Fixed.
