### ISSUE TITLE
Preview window's resizing to content width feature is not working.(neovim only)

### ISSUE THREAD

**Issue by shutils** [Shougo/pum.vim#48]
# Problems summary
Preview window's resizing to content width feature is not working. (neovim only)

## Expected
If the content width is within the preview_height, preview_width range set by the user, the preview window is resized to fit the content width.

## Environment Information (Required!)

- pum.vim version(SHA1):0263631d7cd56caaae58255de24fc8692861a142

- OS:Ubuntu 22.04.2 LTS on Windows 10 x86_64

- neovim/Vim `:version` output:NVIM v0.10.0-dev-836+g6d93bdd45-Homebrew/VIM - Vi IMproved 9.0

## Provide a minimal init.vim/vimrc without plugin managers (Required!)

```vim
set rtp+=/path/to/pum.vim

call pum#set_option(#{
      \   preview: v:true,
      \   preview_border: "single",
      \   preview_height: 10,
      \   preview_width: 30,
      \ })

inoremap <C-n> <Cmd>call pum#map#insert_relative(+1)<CR>
inoremap <C-p> <Cmd>call pum#map#insert_relative(-1)<CR>
inoremap <C-Space> <Cmd>call pum#open(col('.'), [
      \   #{ 
      \     word: 'hoge',
      \     kind: 'Test',
      \     menu: '[test]',
      \     info: "some text.\nsome text."
      \   },
      \ ])<CR>
```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. Press `<C-Space>` in insert mode.
2. Press `<C-n>`.

## Screen shot (if possible)
![cap](https://github.com/Shougo/pum.vim/assets/100141359/113cece4-dc5c-4109-894e-ed2de5ac95d4)

## Upload the log messages by `:redir` and `:message` (if errored)
Notting

**Comment by Shougo** [comment]
Oh, it is bug.

**Comment by Shougo** [comment]
Fixed.

**Comment by shutils** [comment]
Thank you!
