### ISSUE TITLE
pum.vim changes 'backspace' option

### ISSUE THREAD

**Issue by ryota2357** [Shougo/pum.vim#56]
# Problems summary

When I open a floating window and confirm a conversion candidate, the 'backspace' option is changed to 'start'.

## Expected

Do not change 'backspace'.

## Environment Information (Required!)

- pum.vim version(SHA1): latest

- OS: macOS

- neovim/Vim `:version` output:

```
NVIM v0.10.0-dev-1805+gec3c569dd-Homebrew
Build type: Release
LuaJIT 2.1.1700008891
Run ":verbose version" for more info
```

## Provide a minimal init.vim/vimrc without plugin managers (Required!)

```vim
let s:plugins = [
      \ 'vim-denops/denops.vim',
      \ 'Shougo/ddc.vim',
      \ 'Shougo/pum.vim',
      \ 'Shougo/ddc-ui-pum',
      \ 'Shougo/ddc-source-around',
      \ ]

for item in s:plugins
  execute 'set runtimepath+=~/.cache/dein/repos/github.com/' . item
endfor

call ddc#custom#patch_global(#{
 \   ui: 'pum',
 \   sources: ['around'],
 \   autoCompleteEvents: ['InsertEnter', 'TextChangedI', 'TextChangedP', 'CmdlineEnter', 'CmdlineChanged'],
 \ })

inoremap <expr><C-n> pum#visible() ? pum#map#select_relative(+1, "empty") : '<Cmd>normal! gj<CR>'
inoremap <expr><C-p> pum#visible() ? pum#map#select_relative(-1, "empty") : '<Cmd>normal! gk<CR>'
inoremap <expr><CR>  pum#visible() ? pum#map#confirm() : '<CR>'

set backspace=indent,eol,start

call ddc#enable()
```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. type `hoge`.
2. type `hoge` and you can see a popup window with a `hoge` candidate.
3. select `hoge` and confirm it.

## Screenshot (if possible)

https://github.com/Shougo/pum.vim/assets/61523777/bdaeb7fd-4de4-4ab9-9e62-1b10422fb51f

**Comment by Shougo** [comment]
I think `pum.vim` is not the latest.
But I will improve the behavior.

**Comment by Shougo** [comment]
Fixed.
