### ISSUE TITLE
In Neovim, highlighting of selected lines sometimes disappears

### ISSUE THREAD

**Issue by arrow2nd** [Shougo/pum.vim#57]
# Problems summary

In Neovim, highlighting of selected lines sometimes disappears.

It occurs when moving from a candidate with a preview to one without, and vice versa.

## Expected

Highlighting of selected lines remains

## Environment Information (Required!)

- pum.vim version(SHA1): e5a2cb03d9352bb201b90c6278fdfcc8939bcfde

- OS: macOS Sonoma 14.2.1 (M1 Macbook Air)

- Neovim `:version` output: 
````
NVIM v0.10.0-dev-2042+g28c183b38-Homebrew
Build type: Release
LuaJIT 2.1.1703358377
````
## Provide a minimal init.vim/vimrc without plugin managers (Required!)

```vim
syntax enable
filetype plugin indent on

set rtp+=~/temp/denops.vim
set rtp+=~/temp/ddc.vim
set rtp+=~/temp/ddc-ui-pum
set rtp+=~/temp/pum.vim
set rtp+=~/temp/ddc-around
set rtp+=~/temp/ddc-source-cmdline
set rtp+=~/temp/ddc-matcher_head

call ddc#custom#patch_global('sources',
\  [ 'around',  'cmdline' ]
\)

call ddc#custom#patch_global('sourceOptions', {
\  '_': {
\    'matchers': ['matcher_head'],
\  },
\  'around': {
\    'mark': 'A',
\  },
\  'cmdline': {
\    'mark': 'C',
\  }
\})

call ddc#custom#patch_global('autoCompleteEvents', [
\  'InsertEnter', 'TextChangedI', 'TextChangedP',
\])
call ddc#custom#patch_global('ui', 'pum')

call ddc#enable()

call pum#set_option({
\  'auto_select': v:true,
\  'preview': v:true,
\})

imap <script><silent><nowait><expr> <C-n> pum#map#select_relative(+1)
imap <script><silent><nowait><expr> <C-p> pum#map#select_relative(-1)
```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. Type "ec"
2. `<C-n>` to select the candidate below

## Screen shot (if possible)

![画面収録 2024-01-16 7 44 27](https://github.com/Shougo/pum.vim/assets/44780846/18d46db8-084b-463e-9721-36186665b854)

**Comment by Shougo** [comment]
Really?  I have tested your config and I don't reproduce the problem.

**Comment by Shougo** [comment]
I will close if it cannot be reproduce.

**Comment by arrow2nd** [comment]
I tried it with HEAD and it works fine with the vimrc I originally presented.

However, the problem remains that when moving from a candidate with preview to one without preview, when the popup window disappears, the highlight disappears at the same time.

---

Neovim :version output:

```
NVIM v0.10.0-dev-2104+gfd2ed024c
Build type: Release
LuaJIT 2.1.1703358377
```

### minimal .vimrc

```vim
syntax enable
filetype plugin indent on

set rtp+=~/Downloads/temp/denops.vim
set rtp+=~/Downloads/temp/ddc.vim
set rtp+=~/Downloads/temp/ddc-ui-pum
set rtp+=~/Downloads/temp/pum.vim
set rtp+=~/Downloads/temp/ddc-around
set rtp+=~/Downloads/temp/ddc-source-cmdline
set rtp+=~/Downloads/temp/ddc-matcher_head

call ddc#custom#patch_global('sources',
\  [ 'cmdline' ,  'around' ]
\)

call ddc#custom#patch_global('sourceOptions', {
\  '_': {
\    'matchers': ['matcher_head'],
\  },
\  'around': {
\    'mark': 'A',
\  },
\  'cmdline': {
\    'mark': 'C',
\  }
\})

call ddc#custom#patch_global('autoCompleteEvents', [
\  'InsertEnter', 'TextChangedI', 'TextChangedP',
\])
call ddc#custom#patch_global('ui', 'pum')

call ddc#enable()

call pum#set_option({
\  'auto_select': v:true,
\  'preview': v:true,
\})

imap <script><silent><nowait><expr> <C-n> pum#map#select_relative(+1)
imap <script><silent><nowait><expr> <C-p> pum#map#select_relative(-1)
```

### How to reproduce the problem from neovim/Vim startup

- Type "wa"
- <C-n> to select the candidate below

### Screen shot

![画面収録 2024-01-16 22 21 59](https://github.com/Shougo/pum.vim/assets/44780846/a08eb1d9-88d1-41f5-a5ef-4d0a6f23cd21)

**Comment by Shougo** [comment]
Hm...   I will test it later.

**Comment by Shougo** [comment]
Reproduced.  It seems neovim only problem.  Vim works.

**Comment by Shougo** [comment]
Fixed.
