### ISSUE TITLE
highlighted item different to text with ddc.vim

### ISSUE THREAD

**Issue by bon-ami** [Shougo/pum.vim#62]
**Warning: I will close the issue without the minimal init.vim and the
reproduction instructions.**

# Problems summary
When I ^N/^P along the candidates, the auto input words in position are different from the highlighted item in the list.

If I use `dense-analysis/ale`, `statiolake/ddc-ale` and `call ddc#custom#patch_global('sources', ['ale','around'])`, the list splits into two separate parts and the highlights even puzzles me more.

I suspected it was because I did not have noice, but it is the same after I use it.

Thank you in advance.

## Environment Information (Required!)

- pum.vim version(SHA1): e18e30c02eae0463a5837e1ea692f02821fcae0e (2024/8/26)

- OS: Windows 10

- neovim/Vim `:version` output:

## Provide a minimal init.vim/vimrc without plugin managers (Required!)

```vim
" Use Vim settings, rather than Vi settings (much better!).
" This must be first, because it changes other options as a side effect.
set nocompatible
if &cp | set nocp | endif

packadd! matchit

let g:python3_host_prog = 'D:\\apps\\Python3\\python.exe'  " Python 3

call plug#begin()
Plug 'dense-analysis/ale'
" ddc.vim
Plug 'vim-denops/denops.vim'
Plug 'Shougo/ddc-source-around'
Plug 'Shougo/ddc.vim'
Plug 'Shougo/ddc-ui-native'
Plug 'Shougo/ddc-matcher_head'
Plug 'Shougo/ddc-sorter_rank'
Plug 'statiolake/ddc-ale'
Plug 'Shougo/pum.vim'
Plug 'Shougo/ddc-ui-pum'

Plug 'folke/noice.nvim'
Plug 'MunifTanjim/nui.nvim'
"Plug 'rcarriga/nvim-notify'
call plug#end()

lua require("noice").setup()

let g:denops#deno = 'C:\Users\...\.deno\bin\deno.exe'
call ddc#custom#patch_global('ui', 'pum')
call ddc#custom#patch_global('sources', ['around'])
"call ddc#custom#patch_global('sources', ['ale','around'])
call ddc#custom#patch_global('sourceOptions', #{
      \   _: #{
      \     matchers: ['matcher_head'],
      \     sorters: ['sorter_rank']},
      \   },
      \ )
call ddc#custom#patch_global('sourceOptions', #{
	      \   around: #{ mark: 'A' },
	      \ })
call ddc#custom#patch_global('sourceParams', #{
	      \   around: #{ maxSize: 500 },
	      \ })
call ddc#enable()

" Load all plugins now.
" Plugins need to be added to runtimepath before helptags can be generated.
packloadall
" Load all of the helptags now, after plugins have been loaded.
" All messages and errors will be ignored.
silent! helptags ALL
```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. open a go file with a struct containing multiple members
2. enter two letters to show ddc
3. ^N/^P to navigate among the candidates

## Screen shot (if possible)
around only
![pum](https://github.com/user-attachments/assets/66b13d3d-d748-4ddf-b628-12c19b6f94fa)
ale, around
![ale](https://github.com/user-attachments/assets/48f82a99-ec9b-4766-98f3-d6cd2eed5375)

**Comment by Shougo** [comment]
Hm...  I think `ale` works when cursor moved.

Please upload the reproduce instruction.

> open a go file with a struct containing multiple members

Please upload the real file or project.

**Comment by bon-ami** [comment]
pleae save following to test.go. remove s.aaac and insert `s.aa` and ^N/^P to see the issue. Is it omnifunc related?
```go
package main

import "fmt"

func main() {
	fmt.Println("vim-go")
	struct {
		member1, member2, member3 int
		aaaa, aaab, aaac string
	} s
	s.aaac
}
```

**Comment by Shougo** [comment]
Ah, I get it.

`<C-n>`, `<C-p>` is keyword completion.  You must not use them.

**Comment by Shougo** [comment]
It works for me.

```vim
" Use Vim settings, rather than Vi settings (much better!).
" This must be first, because it changes other options as a side effect.
set nocompatible
if &cp | set nocp | endif

set rtp+=~/src/ale
set rtp+=~/work/denops.vim
set rtp+=~/work/ddc-source-around
set rtp+=~/work/ddc.vim
set rtp+=~/work/ddc-ui-native
set rtp+=~/work/ddc-ui-pum
set rtp+=~/work/ddc-filter-matcher_head
set rtp+=~/work/ddc-filter-sorter_rank
set rtp+=~/work/pum.vim
set rtp+=~/src/ddc-ale

call ddc#custom#patch_global('ui', 'pum')
call ddc#custom#patch_global('sources', ['around'])
"call ddc#custom#patch_global('sources', ['ale','around'])
call ddc#custom#patch_global('sourceOptions', #{
      \   _: #{
      \     matchers: ['matcher_head'],
      \     sorters: ['sorter_rank']},
      \   },
      \ )
call ddc#custom#patch_global('sourceOptions', #{
      \   around: #{ mark: 'A' },
      \ })
call ddc#custom#patch_global('sourceParams', #{
      \   around: #{ maxSize: 500 },
      \ })
call ddc#enable()

inoremap <C-n>   <Cmd>call pum#map#insert_relative(+1)<CR>
inoremap <C-p>   <Cmd>call pum#map#insert_relative(-1)<CR>
```

**Comment by bon-ami** [comment]
confirmed. and it is already in README. sorry for the trouble.
